export const cards2 = [
  {
    status: "success",
    totalResults: 1820,
    results: [
      {
        article_id: "941e709ac5f56032c087ebcbb41f6deb",
        link: "https://24newshd.tv/09-Feb-2026/torrential-rain-colombia-leaves-13-dead",
        title: "Torrential rain in Colombia leaves 13 dead",
        description:
          "Thirteen people died this week in Colombia in torrential rain that is rare for this time of year, officials said Sunday.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        keywords: ["topics, environment"],
        creator: ["afp"],
        language: "english",
        country: ["pakistan"],
        category: ["environment"],
        datatype: "news",
        pubDate: "2026-02-09 06:09:26",
        pubDateTZ: "UTC",
        fetched_at: "2026-02-09 06:14:33",
        image_url:
          "https://24newshd.tv/digital_images/large/2026-02-09/representational-image-1770617353-6507.png",
        video_url: null,
        source_id: "newshd24",
        source_name: "24 News Hd",
        source_priority: 758549,
        source_url: "https://www.24newshd.tv",
        source_icon: "https://n.bytvi.com/newshd24.png",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        duplicate: false,
      },
      {
        article_id: "cc49afcf5bd98712b286cfd363ff475c",
        link: "https://www.sportskeeda.com/mma/news-that-s-one-best-attributes-diego-paez-gives-props-ruotolo-brothers-willingness-go-ko",
        title:
          "“That’s one of their best attributes” - Diego Paez gives props to the Ruotolo brothers’ willingness to go for the KO",
        description:
          "ONE flyweight Muay Thai standout, Diego Paez of Colombia and the United States, says the Ruotolo twins, Tye and Kade, are natural martial artists.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        keywords: ["mma"],
        creator: ["ted razon"],
        language: "english",
        country: ["india"],
        category: ["sports"],
        datatype: "news",
        pubDate: "2026-02-09 06:02:02",
        pubDateTZ: "UTC",
        fetched_at: "2026-02-09 07:46:08",
        image_url:
          "https://staticg.sportskeeda.com/editor/2026/02/2e4d8-17703911933848-1920.jpg?w=640",
        video_url: null,
        source_id: "sportskeeda",
        source_name: "Sportskeeda",
        source_priority: 1040,
        source_url: "http://sportskeeda.com",
        source_icon: "https://n.bytvi.com/sportskeeda.png",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        duplicate: false,
      },
      {
        article_id: "653ca2cf30cb6c32a8f13f081a5358dd",
        link: "https://moderndiplomacy.eu/2026/02/09/fernando-boteros-art-is-a-masterpiece-in-body-positivity/",
        title: "Fernando Botero’s Art Is a Masterpiece in Body Positivity",
        description:
          "As I stroll across the streets of Bogota, I come across the Fernando Botero Museum located near the central plaza. Fernando Botero is not new to me. I was introduced to him in Medellin, Colombia, just three days ago as I strolled across Botero Plaza (yes, a plaza dedicated entirely to him) and saw large [...]The post Fernando Botero’s Art Is a Masterpiece in Body Positivity appeared first on Modern Diplomacy.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        keywords: [
          "opinion",
          "arts & culture",
          "painting",
          "art",
          "fernando botero",
        ],
        creator: ["vidhi bubna"],
        language: "english",
        country: ["world"],
        category: ["lifestyle"],
        datatype: "analysis",
        pubDate: "2026-02-09 06:00:47",
        pubDateTZ: "UTC",
        fetched_at: "2026-02-09 06:06:26",
        image_url:
          "https://moderndiplomacy.eu/wp-content/uploads/2026/02/Fernando-Botero.jpg",
        video_url: null,
        source_id: "moderndiplomacy",
        source_name: "Modern Diplomacy",
        source_priority: 43975,
        source_url: "https://moderndiplomacy.eu",
        source_icon: "https://n.bytvi.com/moderndiplomacy.png",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        duplicate: false,
      },
      {
        article_id: "4696ddff19366ce9c48780aa7ecad476",
        link: "https://www.diariodejerez.es/jerez/demanda-empleo-extranjera-jerez-sube_0_2005837806.html",
        title:
          "La demanda de empleo extranjera en Jerez sube casi un 6% en un año",
        description:
          "La contratación de personas procedentes del exterior crece un 3,5% mensual, impulsada principalmente por los servicios y la hosteleríaTrabajos de emergencia en CEIP La Unión, Gloria Fuertes y San Juan de Dios tras el temporal",
        content: "ONLY AVAILABLE IN PAID PLANS",
        keywords: ["últimas noticias jerez"],
        creator: ["a. villegas"],
        language: "spanish",
        country: ["spain"],
        category: ["top", "lifestyle"],
        datatype: "news",
        pubDate: "2026-02-09 06:00:05",
        pubDateTZ: "UTC",
        fetched_at: "2026-02-09 06:16:21",
        image_url:
          "https://static.grupojoly.com/clip/9db1cb12-5c93-4d1e-bec2-3d360953f0d5_facebook-aspect-ratio_default_0.jpg",
        video_url: null,
        source_id: "diariodejerez",
        source_name: "Diario De Jerez",
        source_priority: 1232551,
        source_url: "http://www.diariodejerez.com",
        source_icon: "https://n.bytvi.com/diariodejerez.png",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        duplicate: false,
      },
      {
        article_id: "5f431ddf3b685c0ff011fe8c197c0892",
        link: "https://www.elespectador.com/opinion/columnistas/juan-carlos-gomez/deja-que-los-tecno-oligarcas-ladren/",
        title: "“Deja que los tecno-oligarcas ladren...”",
        description:
          "“Sin duda la tragedia de este siglo es el uso indebido de las redes sociales”.",
        content: "ONLY AVAILABLE IN PAID PLANS",
        keywords: ["columnas juan carlos gomez"],
        creator: ["el espectador"],
        language: "spanish",
        country: ["colombia"],
        category: ["top", "lifestyle"],
        datatype: "news",
        pubDate: "2026-02-09 06:00:00",
        pubDateTZ: "UTC",
        fetched_at: "2026-02-09 06:13:19",
        image_url:
          "https://www.elespectador.com/resizer/v2/KVSCSIEIQRCVDOXMM6AANEVHEQ.jpg?auth=ce76e2f1181e84780174290c4b2dd1d7e5bff5ae10b44c03cf53b85d5c21a13b&focal=512%2C302",
        video_url: null,
        source_id: "elespectador",
        source_name: "Elespectador.com",
        source_priority: 589787,
        source_url: "http://elespectador.com",
        source_icon: null,
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        duplicate: false,
      },
      {
        article_id: "45a195210c48faeea04a0d32bf12ab3a",
        link: "https://www.infobae.com/colombia/deportes/2026/02/09/las-jugadas-clave-de-christian-gonzalez-en-el-super-bowl-asi-brillo-el-colombiano-a-pesar-de-la-derrota-ante-seattle/",
        title:
          "Las jugadas clave de Christian González en el Super Bowl: así brilló el colombiano a pesar de la derrota ante Seattle",
        description:
          "Con intervenciones decisivas, logró frenar varios intentos de anotación de los Seattle Seahawks y se consolidó como uno de los jugadores más consistentes de su equipo en el partido final de la NFL",
        content: "ONLY AVAILABLE IN PAID PLANS",
        keywords: [
          "colombia-noticias",
          "defensa nfl",
          "seattle seahawks",
          "super bowl lx",
          "colombia-deportes",
          "christian gonzález",
          "new england patriots",
          "jugador colombiano",
        ],
        creator: ["dahana ospina"],
        language: "spanish",
        country: [
          "united states of america",
          "colombia",
          "mexico",
          "argentina",
        ],
        category: ["top", "lifestyle"],
        datatype: "news",
        pubDate: "2026-02-09 05:55:53",
        pubDateTZ: "UTC",
        fetched_at: "2026-02-09 06:00:45",
        image_url:
          "https://www.infobae.com/resizer/v2/NT4AXIMDYREUZEF4QXYFT6KEZE.jpg?auth=e5a49fee40604c9c1bb12202422c7ba9c23198c8985ced5755a72940f49b4758&height=1080&smart=true&width=1920",
        video_url: null,
        source_id: "infobae",
        source_name: "Infobae",
        source_priority: 1056,
        source_url: "https://www.infobae.com",
        source_icon: "https://n.bytvi.com/infobae.png",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        duplicate: false,
      },
      {
        article_id: "c714d54de1ac16421d1108bc59377c88",
        link: "https://www.kgw.com/article/syndication/associatedpress/nicaraguan-government-blocks-key-pathway-used-by-cuban-migrants-to-reach-united-states/616-401fc4db-a71c-47a9-81ca-2b49b1d21961",
        title:
          "Nicaraguan government blocks key pathway used by Cuban migrants to reach United States",
        description:
          "Nicaragua's government blocks Cuban citizens from entering without a visa, cutting off a key migration route to the U.S. The government confirmed this change on...",
        content: "ONLY AVAILABLE IN PAID PLANS",
        keywords: ["associatedpress", "syndication"],
        creator: ["megan janetsky"],
        language: "english",
        country: ["united states of america"],
        category: ["politics"],
        datatype: "news",
        pubDate: "2026-02-09 05:42:49",
        pubDateTZ: "UTC",
        fetched_at: "2026-02-09 07:02:34",
        image_url: null,
        video_url: null,
        source_id: "kgw",
        source_name: "Kgw",
        source_priority: 3758,
        source_url: "http://www.kgw.com",
        source_icon: "https://n.bytvi.com/kgw.jpg",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        duplicate: true,
      },
      {
        article_id: "b04546a2c9897750996f0679671a528c",
        link: "https://www.khou.com/article/syndication/associatedpress/nicaraguan-government-blocks-key-pathway-used-by-cuban-migrants-to-reach-united-states/616-401fc4db-a71c-47a9-81ca-2b49b1d21961",
        title:
          "Nicaraguan government blocks key pathway used by Cuban migrants to reach United States",
        description:
          "Nicaragua's government blocks Cuban citizens from entering without a visa, cutting off a key migration route to the U.S. The government confirmed this change on...",
        content: "ONLY AVAILABLE IN PAID PLANS",
        keywords: ["syndication", "associatedpress"],
        creator: ["megan janetsky"],
        language: "english",
        country: ["united states of america"],
        category: ["top", "politics"],
        datatype: "news",
        pubDate: "2026-02-09 05:42:49",
        pubDateTZ: "UTC",
        fetched_at: "2026-02-09 07:04:11",
        image_url: null,
        video_url: null,
        source_id: "khou",
        source_name: "Khou",
        source_priority: 14652,
        source_url: "https://www.khou.com",
        source_icon: "https://n.bytvi.com/khou.png",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        duplicate: true,
      },
      {
        article_id: "a7616f10c704c5c6415892ada9449b36",
        link: "https://www.chronicleonline.com/news/world/nicaraguan-government-blocks-key-pathway-used-by-cuban-migrants-to-reach-united-states/article_b2a60f5b-08ff-58b6-8b26-4c606a21ae52.html",
        title:
          "Nicaraguan government blocks key pathway used by Cuban migrants to reach United States",
        description:
          "Nicaragua's government blocks Cuban citizens from entering without a visa, cutting off a key migration route to the U.S. The government confirmed this change on Sunday, suspending an exemption that allowed Cubans to enter visa-free. For years, Cubans flew to...",
        content: "ONLY AVAILABLE IN PAID PLANS",
        keywords: [
          "immigration",
          "general news",
          "cuba nicaragua migrants trump us",
          "politics",
          "asylum",
          "u.s.-venezuela conflict",
          "world news",
        ],
        creator: ["by megan janetsky - associated press"],
        language: "english",
        country: ["united states of america"],
        category: ["top", "politics"],
        datatype: "news",
        pubDate: "2026-02-09 05:42:49",
        pubDateTZ: "UTC",
        fetched_at: "2026-02-09 09:36:20",
        image_url:
          "https://bloximages.newyork1.vip.townnews.com/chronicleonline.com/content/tncms/assets/v3/editorial/2/29/229f63a4-7ef4-5e3a-a746-476ed9cc9b5e/698788b8ade1b.image.jpg?resize=300%2C200",
        video_url: null,
        source_id: "chronicleonline",
        source_name: "Chronicle Online",
        source_priority: 34928,
        source_url: "https://www.chronicleonline.com",
        source_icon: "https://n.bytvi.com/chronicleonline.jpg",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        duplicate: true,
      },
      {
        article_id: "de99d650abad113e0a3e4cfa06f48a19",
        link: "https://www.12news.com/article/syndication/associatedpress/nicaraguan-government-blocks-key-pathway-used-by-cuban-migrants-to-reach-united-states/616-401fc4db-a71c-47a9-81ca-2b49b1d21961",
        title:
          "Nicaraguan government blocks key pathway used by Cuban migrants to reach United States",
        description:
          "Nicaragua's government blocks Cuban citizens from entering without a visa, cutting off a key migration route to the U.S. The government confirmed this change on...",
        content: "ONLY AVAILABLE IN PAID PLANS",
        keywords: ["associatedpress", "syndication"],
        creator: ["megan janetsky"],
        language: "english",
        country: ["united states of america"],
        category: ["politics"],
        datatype: "news",
        pubDate: "2026-02-09 05:42:49",
        pubDateTZ: "UTC",
        fetched_at: "2026-02-09 07:49:21",
        image_url: null,
        video_url: null,
        source_id: "a12news",
        source_name: "12news",
        source_priority: 24546,
        source_url: "https://www.12news.com",
        source_icon: "https://n.bytvi.com/a12news.png",
        sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
        ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
        ai_summary: "ONLY AVAILABLE IN PAID PLANS",
        duplicate: true,
      },
    ],
    nextPage: "1770615769302162046",
  },
];
